/**
 * Asset pipeline (Phase 8 fusion spike): normalize vendored Open Peeps parts
 * (CC0 artwork, see remotion/assets/peeps/LICENSE.md) into typed TS part
 * definitions. Deterministic + re-runnable: parses the raw react-peeps part
 * files, extracts each SVG path's `d` + its translate + role (skin vs ink),
 * and writes remotion/src/drawing/peeps.ts.
 *
 * Open Peeps head composition (from react-peeps head/index.js): the head group
 * places the HAIR piece at its origin and the FACE piece at translate(159,186).
 * A hair piece = a `backgroundColor` path (the head SKIN) + `strokeColor`
 * path(s) (the hair). A face piece = `strokeColor` filled feature shapes.
 *
 * Usage: tsx pipeline/extract_peeps.ts
 */
import { readFileSync, writeFileSync, readdirSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const REPO = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const RAW = join(REPO, "remotion", "assets", "peeps", "raw");

type PeepsPath = { d: string; role: "skin" | "ink"; tx: number; ty: number; evenodd: boolean };

/** Pull every <path> createElement out of one compiled part file, in order. */
function parsePart(src: string): PeepsPath[] {
  const out: PeepsPath[] = [];
  // Each path element is an object literal with d / transform / fill / fillRule.
  // Split on 'createElement("path"' and parse each following {...}.
  const chunks = src.split(/createElement\(\s*["']path["']/).slice(1);
  for (const ch of chunks) {
    const d = ch.match(/\bd:\s*'([^']*)'/)?.[1];
    if (!d) continue;
    const tr = ch.match(/transform:\s*'translate\(([-\d.]+)\s+([-\d.]+)\)'/);
    const tx = tr ? parseFloat(tr[1]!) : 0;
    const ty = tr ? parseFloat(tr[2]!) : 0;
    const fill = ch.match(/\bfill:\s*([a-zA-Z]+)/)?.[1] ?? "strokeColor";
    const role: "skin" | "ink" = fill === "backgroundColor" ? "skin" : "ink";
    const evenodd = /fillRule:\s*'evenodd'/.test(ch);
    out.push({ d, role, tx, ty, evenodd });
  }
  return out;
}

function round(p: PeepsPath): PeepsPath {
  return { ...p, tx: Math.round(p.tx * 100) / 100, ty: Math.round(p.ty * 100) / 100 };
}

function main() {
  const files = readdirSync(RAW).filter((f) => f.endsWith(".js"));
  const hair: Record<string, PeepsPath[]> = {};
  const face: Record<string, PeepsPath[]> = {};
  for (const f of files) {
    const [cat, nameJs] = f.split("_");
    const name = nameJs!.replace(/\.js$/, "");
    const paths = parsePart(readFileSync(join(RAW, f), "utf8")).map(round);
    if (cat === "hair") hair[name] = paths;
    else if (cat === "face") face[name] = paths;
    console.log(`  ${f.padEnd(22)} ${paths.length} path(s)  [${paths.map((p) => p.role).join(",")}]`);
  }

  const header = `// AUTO-GENERATED by pipeline/extract_peeps.ts — do not edit by hand.
// Open Peeps artwork (CC0, Pablo Stanley) extracted from the react-peeps MIT
// port. See remotion/assets/peeps/LICENSE.md. Coordinates are Open Peeps native
// (head-group space): hair paths at (tx,ty); FACE paths offset by (159,186).
export type PeepsPath = { d: string; role: "skin" | "ink"; tx: number; ty: number; evenodd: boolean };
export const PEEPS_FACE_OFFSET = { x: 159, y: 186 } as const;
`;
  const body =
    `export const PEEPS_HAIR: Record<string, PeepsPath[]> = ${JSON.stringify(hair)};\n` +
    `export const PEEPS_FACE: Record<string, PeepsPath[]> = ${JSON.stringify(face)};\n`;

  const outPath = join(REPO, "remotion", "src", "drawing", "peeps.ts");
  writeFileSync(outPath, header + "\n" + body);
  console.log(`\n✓ wrote ${outPath}  (${Object.keys(hair).length} hair, ${Object.keys(face).length} face)`);
}

main();
